notifications:
  email: false

language: node_js

node_js:
  - 'stable'
  - '0.12'

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
